### ISSUE TITLE
making the repo private

### ISSUE THREAD

**Issue by hpourreza** [rcc-uchicago/skyway#1]
@yuxingpeng Could you please make this repo private so RCC staff can put their code while testing Skyway?

**Comment by pcarbo** [comment]
@hpourreza It looks like that we have reached our limit on the number of private repos. We would have to delete a private repo or make it public before making this repo private.

**Comment by pcarbo** [comment]
@hpourreza I made the repo private after setting `rcc-uchicago/R-midway` to be public.
